apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notifaction-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore 
    name: akeyless-secret-store

  target:
    name: notifaction-secrets
    creationPolicy: Owner
