service: notification

api:
  port: 9080
  debug: true
  test: true


log:
  level: debug
  target: os

mail:
  from: "\"OOSA Group\" <developer@oosa.life>"
  template:
    source: aws
  provider: smtp # aws | smtp
  header2data:
  - X-Forwarded-Host
  

aws:
  ses: 
    region: ap-northeast-1
    credentails:
      filename: /Users/peter/Codes/oosa/secrets/.aws/credentails
      profile: default

identity:
  url: http://localhost:4434

smtp:
  url: smtp://localhost:25