apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: notifaction-app-set
spec:
  generators:
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/arwoosa/notifaction.git
              revision: cd
              directories:
              - path: argocd/overlays/*
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  type: '{{path.basename}}'
  template: # used to generate Argo CD Application resources
    metadata:
      name: 'sso-notifaction-{{path.basename}}'
    spec:
      project: oosa
      source:
        repoURL: https://github.com/arwoosa/notifaction.git
        targetRevision: cd
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: 'oosa-sso'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true